name: Ruby Gem

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest','macos-latest' ]
        # - https://www.ruby-lang.org/en/downloads/branches
        ruby: [ '3.1','ruby-head','jruby-head' ]

    runs-on: "${{ matrix.os }}"

    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # - https://github.com/ruby/setup-ruby
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler: 'latest'
        bundler-cache: true
#        cache-version: 1

#    - name: Install Gems
#      run: |
#        gem update bundler
#        bundle install

    - name: Run tests
      run: bundle exec rake test

    - name: Test doc
      run: bundle exec rake doc

    - name: Test build & install
      run: |
        bundle exec rake build
        gem install --document --local pkg/*.gem
        ruby -w -r attr_bool -e 'puts AttrBool::VERSION'
